export const LOAD_STARSHIPS = "LOAD_STARSHIPS";
export const LOAD_STARSHIPS_SUCCESS = "LOAD_STARSHIPS_SUCCESS";
export const ADD_PASSENGERS_TO_STARSHIP = "ADD_PASSENGERS_TO_STARSHIP";
export const REMOVE_PASSENGERS_FROM_STARSHIP =
  "REMOVE_PASSENGERS_FROM_STARSHIP";
export const ADD_STARSHIP_TO_FLEET = "ADD_STARSHIP_TO_FLEET";
export const REMOVE_STARSHIP_FROM_FLEET = "REMOVE_STARSHIP_FROM_FLEET";
